networks:
  api-network:

volumes:
  rabbitmq_data:
  generator_data:
  insurance_db:

services:
  insurance-data-generator:
    build: ./insurance-data-generator
    container_name: insurance-data-generator
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSWORD: admin
    networks:
      - api-network
    volumes:
      - generator_data:/app/data

  insurance-db:
    image: postgres:18.0-alpine
    container_name: insurance-db
    restart: always
    environment:
      POSTGRES_DB: insurance-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - api-network
    volumes:
      - insurance_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d insurance-db"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4.3.2-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672" # management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - api-network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
