spark {
    url = ${?SPARK_URL}
}

datasource {
    jdbc = "jdbc:postgresql://localhost:5432/insurance-db"
    jdbc = ${?POSTGRES_URL}
    username = "postgres"
    username = ${?POSTGRES_USER}
    password = "postgres"
    password = ${?POSTGRES_PASSWORD}
}

minio {
  endpoint = "http://localhost:9000"
  endpoint = ${?MINO_ENDPOINT}
  access-key = "minioadmin"
  access-key = ${?MINO_USERNAME}
  secret-key = "minioadmin"
  secret-key = ${?MINO_PASSWORD}
  bucket = "raw-data/"
  bucket = ${?MINO_BUCKET}
}
