datasource {
    jdbc = "jdbc:postgresql://localhost:5432/insurance-db"
    jdbc = ${?POSTGRES_URL}
    username = "postgres"
    username = ${?POSTGRES_USER}
    password = "postgres"
    password = ${?POSTGRES_PASSWORD}
}
