server {
  host = "0.0.0.0"
  host = ${?SERVER_HOST}
  port = 8080
  port = ${?SERVER_PORT}
}

rabbitmq {
  host = "localhost"
  host = ${?RABBITMQ_HOST}
  port = 5672
  port = ${?RABBITMQ_PORT}
  username = "admin"
  username = ${?RABBITMQ_USERNAME}
  password = "admin"
  password = ${?RABBITMQ_PASSWORD}
}

minio {
  endpoint = "http://localhost:9000"
  endpoint = ${?MINO_ENDPOINT}
  access-key = "minioadmin"
  access-key = ${?MINO_USERNAME}
  secret-key = "minioadmin"
  secret-key = ${?MINO_PASSWORD}
  bucket = "raw-data"
  bucket = ${?MINO_BUCKET}
}
